# Generated by Django 3.1.2 on 2020-12-22 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orla', '0002_auto_20201221_0804'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='logo',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
