# Generated by Django 3.1.3 on 2020-11-14 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anuncio',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
